### ISSUE TITLE
Exception in browser console when trying to migrate repositoty without trunk

### ISSUE THREAD

**Issue by Nodwick** [yodamad/svn2git#167]
The button stays disabled
![image](https://github.com/user-attachments/assets/b5d20f3a-bb41-4730-ac90-f2bbcdf7d07b)

ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'uppercase')
TypeError: Cannot read properties of undefined (reading 'uppercase')
    at 467.l.initMigration (main.e56a3e67360ec9349837.bundle.js:1:432556)
    at l.<anonymous> (main.e56a3e67360ec9349837.bundle.js:1:430720)
    at 0.e56a3e67360ec9349837.chunk.js:1:1500807
    at Object.next (0.e56a3e67360ec9349837.chunk.js:1:1500912)
    at 0.e56a3e67360ec9349837.chunk.js:1:1499850
    at new t (0.e56a3e67360ec9349837.chunk.js:1:2042412)
    at Object.o (0.e56a3e67360ec9349837.chunk.js:1:1499627)
    at 467.l.go (main.e56a3e67360ec9349837.bundle.js:1:430531)
    at Object.handleEvent (main.e56a3e67360ec9349837.bundle.js:1:627752)
    at Object.handleEvent (0.e56a3e67360ec9349837.chunk.js:1:148781)
    at 467.l.initMigration (main.e56a3e67360ec9349837.bundle.js:1:432556)
    at l.<anonymous> (main.e56a3e67360ec9349837.bundle.js:1:430720)
    at 0.e56a3e67360ec9349837.chunk.js:1:1500807
    at Object.next (0.e56a3e67360ec9349837.chunk.js:1:1500912)
    at 0.e56a3e67360ec9349837.chunk.js:1:1499850
    at new t (0.e56a3e67360ec9349837.chunk.js:1:2042412)
    at Object.o (0.e56a3e67360ec9349837.chunk.js:1:1499627)
    at 467.l.go (main.e56a3e67360ec9349837.bundle.js:1:430531)
    at Object.handleEvent (main.e56a3e67360ec9349837.bundle.js:1:627752)
    at Object.handleEvent (0.e56a3e67360ec9349837.chunk.js:1:148781)
    at T (0.e56a3e67360ec9349837.chunk.js:1:2041422)
    at new t (0.e56a3e67360ec9349837.chunk.js:1:2042444)
    at Object.o (0.e56a3e67360ec9349837.chunk.js:1:1499627)
    at 467.l.go (main.e56a3e67360ec9349837.bundle.js:1:430531)
    at Object.handleEvent (main.e56a3e67360ec9349837.bundle.js:1:627752)
    at Object.handleEvent (0.e56a3e67360ec9349837.chunk.js:1:148781)
    at Object.handleEvent (0.e56a3e67360ec9349837.chunk.js:1:159966)
    at mc (0.e56a3e67360ec9349837.chunk.js:1:118652)
    at 0.e56a3e67360ec9349837.chunk.js:1:140147
    at e._next (0.e56a3e67360ec9349837.chunk.js:1:59515)

**Comment by Nodwick** [comment]
The relevant button is marked in the screenshot

**Comment by yodamad** [comment]
Ok I'll have a look
Any logs from the backend ?

**Comment by yodamad** [comment]
@Nodwick : can you tell me more about your use-case : no trunk ? but is there branches & tags folders ? or all sources are directly within the directory ?

**Comment by Nodwick** [comment]
No logging is happening on the backend when I click the button in the browser. I guess that no requests happen because the error stops the execution.

There are only files checked directly into the svn (Eclipse SVN view).
![image](https://github.com/user-attachments/assets/35fb739b-bcba-4cb2-95d8-d5a39299c448)
Compare with another repository that contains branches, tags and a trunk
![image](https://github.com/user-attachments/assets/810d2a90-616f-4a3f-836b-659c35d7424d)

**Comment by yodamad** [comment]
Ok thank you for the info, I'll check if I can reproduce and let you know

**Comment by yodamad** [comment]
@Nodwick : I've reproduced and fixed the bug, I'll try to release later today
